# Generated by Django 3.0.2 on 2020-01-12 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_publication'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publication',
            name='image',
        ),
        migrations.AddField(
            model_name='publication',
            name='publicationtype',
            field=models.CharField(default='Unknown', max_length=1024),
        ),
        migrations.AddField(
            model_name='publication',
            name='title',
            field=models.CharField(default='-', max_length=1024),
        ),
        migrations.AddField(
            model_name='publication',
            name='year',
            field=models.IntegerField(default=2020),
        ),
    ]
