# Generated by Django 3.0.2 on 2020-01-16 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_auto_20200112_1356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facultyprofile',
            name='about',
            field=models.TextField(max_length=1024),
        ),
    ]
