# Generated by Django 3.0.2 on 2020-01-22 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0007_auto_20200120_1614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facultyprofile',
            name='articles',
            field=models.TextField(blank=True, max_length=1024),
        ),
        migrations.AlterField(
            model_name='facultyprofile',
            name='projects',
            field=models.TextField(blank=True, max_length=1024),
        ),
    ]
