# Generated by Django 3.0.2 on 2020-01-22 17:04

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0008_auto_20200122_1400'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facultyprofile',
            name='about',
            field=ckeditor.fields.RichTextField(max_length=1024),
        ),
        migrations.AlterField(
            model_name='facultyprofile',
            name='articles',
            field=ckeditor.fields.RichTextField(blank=True, max_length=1024),
        ),
        migrations.AlterField(
            model_name='facultyprofile',
            name='projects',
            field=ckeditor.fields.RichTextField(blank=True, max_length=1024),
        ),
    ]
