# Generated by Django 3.0.2 on 2020-02-03 03:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('profiles', '0009_auto_20200122_1704'),
    ]

    operations = [
        migrations.AddField(
            model_name='facultyprofile',
            name='bookmark',
            field=models.ManyToManyField(blank=True, related_query_name='bookmark', to=settings.AUTH_USER_MODEL),
        ),
    ]
